import type { NextPage } from 'next'
import Head from 'next/head'



const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>My awesome dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <main className="">
        <div className="py-32 text-center max-w-5xl mx-auto text-center">

          <h1 className="text-6xl font-bold dark:text-white ">
            My awesome <span className="text-indigo-600">dapp</span>
          </h1>
          <p className='py-12 text-lg'>This is a template that you can use a starting point for your web3 applications. Built with <a href="https://nextjs.org" className="underline" target="_blank" rel="noreferrer">
										Next.js
									</a>{' '}
									and{' '}
									<a
										href="https://tailwindcss.com"
										className="underline"
										target="_blank"
										rel="noreferrer"
									>
										Tailwind CSS
									</a>
									, with{' '}
									<a
										href="https://docs.family.co/connectkit"
										className="underline"
										target="_blank"
										rel="noreferrer"
									>
										ConnectKit
									</a></p>
        </div>

      </main>

  
    </div>

  )
}

export default Home
